Remove qb-menu and qb-target
Qbox-project/qb-taxijob pull request #2
Opened 2023-01-22 18:05 UTC by JoeSzymkowiczFiveM

**Describe Pull request**
Shift taxijob to ox resources, remove Polyzone and qb-target, qb-menu. Retaining existing functionality prior to push.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2023-01-22 18:14 UTC, BerkieBb requested changes

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +    if resourceName == GetCurrentResourceName() and QBCore.Functions.GetPlayerData() ~= {} then
`~= {}` doesn't work, instead use `table.type(QBCore.Functions.GetPlayerData()) ~= 'empty'`

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +    if resourceName == GetCurrentResourceName() and QBCore.Functions.GetPlayerData() ~= {} then
And you can invert both if statements here and combine them into `if resource ~= GetCurrentResourceName() or table.type(QBCore.Functions.GetPlayerData()) == 'empty' or not Config.UseTarget then return end`

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +AddEventHandler('onResourceStart', function(resourceName)
Same as above

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +                        Wait(1)
Reduce to wait 0

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +                                    lastLocation = GetEntityCoords(PlayerPedId())
Use ped here

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +    local resgisteredMenu = {
resgistered

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +    resgisteredMenu["options"] = options
Just .options is fine

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +                        local ped = PlayerPedId()
You can use cache.ped instead

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +                                    local veh = GetVehiclePedIsIn(ped, 0)
You can use cache.vehicle instead

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +        RequestModel(`a_m_m_indian_01`)
Instead of these 4 lines, use lib.requestModel

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
> +        exports['qb-core']:DrawText(Lang:t("info.call_npc"), Config.DefaultTextLocation)
Use lib.drawText instead

2023-01-22 18:14 UTC, BerkieBb commented on client/main.lua
>              Wait(1)
wait 0

2023-01-22 18:15 UTC, BerkieBb commented
Aside from my reviews, make local functions out of the current global ones as I don't think they're used globally, invert if statements to reduce indentation and fix the issues with the linter

2023-01-23 19:53 UTC, JoeSzymkowiczFiveM commented on client/main.lua
> +                        Wait(1)
Updated this.

2023-01-23 19:53 UTC, JoeSzymkowiczFiveM commented on client/main.lua
> +                                    lastLocation = GetEntityCoords(PlayerPedId())
Updated to use cache.

2023-01-23 19:54 UTC, JoeSzymkowiczFiveM commented on client/main.lua
> +    local resgisteredMenu = {
Corrected misspelling

2023-01-23 19:54 UTC, JoeSzymkowiczFiveM commented on client/main.lua
> +                        local ped = PlayerPedId()
Updated to use cache

2023-01-23 19:54 UTC, JoeSzymkowiczFiveM commented on client/main.lua
> +                                    local veh = GetVehiclePedIsIn(ped, 0)
Updated to use cache.

2023-01-23 19:54 UTC, JoeSzymkowiczFiveM commented on client/main.lua
>              Wait(1)
Updated interval

2023-01-23 19:54 UTC, JoeSzymkowiczFiveM commented on client/main.lua
> +        exports['qb-core']:DrawText(Lang:t("info.call_npc"), Config.DefaultTextLocation)
Updated to use lib.showTextUI

2023-01-27 19:36 UTC, ChatDisabled commented
@YvanCywan I'll overrule that for now 😃

2023-01-27 19:37 UTC, merged